### DISCUSSION TITLE
Snap Maintenance Thread

### DISCUSSION THREAD

**Discussion by soumyaDghosh** [saber-notes/saber#475] [Ideas]
With the latest attempt, I have made it possible to use the two finger pinch to zoom in. 
This is the `snapcraft.yaml` file. Check this out. I hope this is now much much stable, with core22.
<details>
<summary>snapcraft.yaml</summary>

```yaml
name: saber # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.9.8' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64


parts:
  desktop:
    after: [saber, flutter-git]
    source: .
    plugin: dump
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.7.7 # run local/flutter/update-artifacts.sh [x.y.z]
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''
  saber:
    after: [flutter-git]
    source: https://github.com/adil192/saber.git
    source-type: git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    plugin: nil
    #build-attributes: [enable-patchelf]
    build-packages:
      - jq
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-0
      - libjsoncpp25
      - zenity
    override-build: |
      set -eux
      flutter pub get || true
      flutter build linux --release
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

apps:
  saber:
    command: bin/saber
    desktop: snap/meta/gui/saber.desktop
    extensions: [gnome]
    common-id: com.adilhanney.saber
    plugs:
      - home
      - network
      - network-status
```
</details>
